/**
 * render/metadataTable.js — turns a location object into a readable table.
 *
 * The table is GENERATED by walking the JSON object, not written by hand:
 * adding a property to locations.json adds a row automatically.
 *
 *  - LABELS gives a readable name to known properties; unknown ones get an
 *    automatic label ("lmml:shootingDate" -> "Shooting date").
 *  - SKIP lists properties shown elsewhere on the page (texts, images).
 *  - Objects of some schema.org types are shown on one line (TYPE_FORMATTERS:
 *    an address, coordinates, a person). Other objects (e.g. the Movie) are
 *    EXPANDED into sub-rows: "Appears in › Name", "Appears in › Released", …
 *  - Empty values (null, "", []) are not shown.
 */
import { el, externalLink } from '../dom.js';

const LABELS = {
  '@type': 'Type',
  name: 'Name',
  address: 'Address',
  geo: 'Coordinates',
  'lmml:cameraPosition': 'Camera position',
  'lmml:cameraBearing': 'Camera direction',
  'lmml:shotDescription': 'How to find the shot',
  'lmml:verified': 'Verified',
  'lmml:appearsIn': 'Appears in',
  'lmml:sceneDescription': 'Scene',
  'lmml:representsPlace': 'Plays the role of',
  datePublished: 'Released',
  director: 'Director',
  episodeNumber: 'Episode',
  partOfSeason: 'Season',
  partOfSeries: 'Series',
  citation: 'Sources',
};

const SKIP = new Set(['@context', 'identifier', 'image', 'lmml:texts']);

/** One-line rendering of whole objects, chosen by their schema.org @type. */
const TYPE_FORMATTERS = {
  GeoCoordinates: (v) => externalLink(
    `https://www.openstreetmap.org/?mlat=${v.latitude}&mlon=${v.longitude}#map=19/${v.latitude}/${v.longitude}`,
    `${v.latitude}, ${v.longitude}`),
  PostalAddress: (v) => [v.streetAddress, v.postalCode, v.addressLocality].filter(Boolean).join(', '),
  Person: (v) => v.name,
  Place: (v) => v.name,
  TVSeries: (v) => v.name,
  TVSeason: (v) => (v.seasonNumber != null ? `Season ${v.seasonNumber}` : null),
  CreativeWork: (v) => el('span', {}, externalLink(v.url), v.description ? ` — ${v.description}` : ''),
};

/** Special rendering of single properties, chosen by property name. */
const KEY_FORMATTERS = {
  'lmml:cameraBearing': (v) => `${v}° from north (${compass(v)})`,
  'lmml:verified': (v) => (v ? 'Yes' : 'No — to be checked'),
};

export function buildMetadataTable(loc) {
  const tbody = el('tbody');
  addRows(tbody, loc, [], true);
  return el('table', { 'data-role': 'metadata-table' },
    el('caption', { 'data-role': 'metadata-caption' }, 'Metadata'),
    tbody);
}

/**
 * Add one row per property of obj. path = labels of the parent objects,
 * so nested rows read "Appears in › Director".
 */
function addRows(tbody, obj, path, isRoot) {
  for (const [key, value] of Object.entries(obj)) {
    if (SKIP.has(key) || isEmpty(value)) continue;
    if (key === '@type' && isRoot) continue; // "Place" on the root is not informative

    const labels = [...path, labelFor(key)];
    const rendered = renderValue(key, value);

    if (rendered === undefined) {
      addRows(tbody, value, labels, false); // an object without formatter: expand it
    } else if (rendered !== null) {
      tbody.append(
        el('tr', { 'data-key': key, 'data-depth': path.length },
          el('th', { scope: 'row' }, labels.join(' › ')),
          el('td', {}, rendered)),
      );
    }
  }
}

/** Returns a string/Node to show, null to hide, or undefined for "expand into sub-rows". */
function renderValue(key, value) {
  if (KEY_FORMATTERS[key]) return KEY_FORMATTERS[key](value);

  if (Array.isArray(value)) {
    return el('ul', { 'data-role': 'metadata-list' },
      value.map((item) => el('li', {}, renderValue(key, item) ?? JSON.stringify(item))));
  }
  if (typeof value === 'object') {
    const formatter = TYPE_FORMATTERS[value['@type']];
    return formatter ? formatter(value) : undefined;
  }
  if (typeof value === 'boolean') return value ? 'Yes' : 'No';
  if (typeof value === 'string' && /^https?:\/\//.test(value)) return externalLink(value);
  return String(value);
}

/** null, undefined, '', [] and objects whose values are all empty. */
function isEmpty(value) {
  if (value === null || value === undefined || value === '') return true;
  if (Array.isArray(value)) return value.length === 0;
  if (typeof value === 'object') {
    return Object.entries(value).every(([k, v]) => k === '@type' || isEmpty(v));
  }
  return false;
}

/** Automatic label: strip the prefix, split camelCase. "lmml:shootingDate" -> "Shooting date" */
function labelFor(key) {
  if (LABELS[key]) return LABELS[key];
  const words = key.replace(/^[a-z]+:/, '').replace(/([a-z])([A-Z])/g, '$1 $2').toLowerCase();
  return words.charAt(0).toUpperCase() + words.slice(1);
}

/** 0..360 degrees -> one of 8 compass points. */
function compass(degrees) {
  const points = ['N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW'];
  const normalised = ((degrees % 360) + 360) % 360;
  return points[Math.round(normalised / 45) % 8];
}
